In [2]:
import numpy as np

#### np.asarray(a, dtype=None, order=None): 
将结构数据转化为ndarray
* a：可以是列表、列表的元组、元组、元组的元组、元组的列表或多维数组
* dtype：数据类型，默认的是自己从输入的数据自动获得
    * 'f'：float类型
    * 'i'：int类型
* order：有"C"和"F"两个选项,分别代表，行优先和列优先，在计算机内存中的存储元素的顺序

In [4]:
a= [1,2]
np.asarray(a,'f')

array([1., 2.], dtype=float32)

In [5]:
a = [[1,2],[1,0]]
a = np.asarray(a)#必须先转换为array，否则出现array(1.0, dtype=float32)
np.asarray(a>0,'i')#'i'表示为dtype类型为int

array([[1, 1],
       [1, 0]], dtype=int32)

In [6]:
np.asarray(a>0,'f')

array([[1., 1.],
       [1., 0.]], dtype=float32)