In [1]:
import numpy as np

### 创建数组

In [2]:
np.array([1, 2, 3, 4, 5]) # 把列表转换为数组

array([1, 2, 3, 4, 5])

In [3]:
np.array((1, 2, 3, 4, 5)) # 把元组转换成数组

array([1, 2, 3, 4, 5])

In [4]:
np.array(range(5))    # 把range对象转换成数组

array([0, 1, 2, 3, 4])

In [5]:
np.arange(8) 

array([0, 1, 2, 3, 4, 5, 6, 7])

In [6]:
np.arange(1, 10, 2)


array([1, 3, 5, 7, 9])

In [7]:
np.linspace(0, 10, 11)    # 等差数组，包含11个数

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [8]:
np.zeros(3)             # 全0一维数组

array([0., 0., 0.])

In [9]:
np.identity(3)        # 单位矩阵

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.empty((3,3))    # 空数组，只申请空间而不初始化，元素值是不确定的

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.random.randint(0, 50, 5)     
                 # 随机一维数组，5个0到50之间的数字

array([14, 47, 21, 19,  8])

In [12]:
np.random.randint(0, 50, (3,5)) 
                            # 随机二维数组，3行5列

array([[21, 41, 49, 18, 14],
       [25, 19, 48, 23,  7],
       [ 2,  0, 26, 16, 48]])

In [13]:
np.random.rand(10) # 10个0到1之间的随机数

array([0.20487304, 0.44825228, 0.43004851, 0.39651615, 0.24477423,
       0.47668283, 0.68298335, 0.14409349, 0.84720911, 0.01717763])

In [14]:
np.random.standard_normal(5)    # 从标准正态分布中随机采样

array([ 1.15721417,  0.54081893,  0.19944032,  1.51781376, -0.1077584 ])

In [15]:
np.random.choice(range(100), 3)  
                          # 随机选择3个数

array([47, 92, 23])

In [16]:
np.random.choice((1,-1), (3,5))  
                          # 3行5列随机数，均为-1或1

array([[-1,  1,  1, -1, -1],
       [ 1,  1, -1,  1, -1],
       [-1,  1,  1, -1,  1]])

In [17]:
np.diag([1,2,3])            # 对角矩阵

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

### 改变数组元素

In [20]:
x = np.arange(8)
x1=np.append(x, 9)         # 追加元素
print(x1)
x2=np.insert(x, 2, 9)      # 插入元素
print(x2)
x3=np.delete(x, 2)         # 删除元素
print(x3)
print(x) # 原数组不变

[0 1 2 3 4 5 6 7 9]
[0 1 9 2 3 4 5 6 7]
[0 1 3 4 5 6 7]
[0 1 2 3 4 5 6 7]


原地修改：用下标

In [21]:
x[0]=100
print(x) # 原数组改变

[100   1   2   3   4   5   6   7]


### 数组转置

In [22]:
b = np.array(([1, 2, 3], [4, 5, 6], [7, 8, 9]))
print(b)
print(b.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


### 排序

In [24]:
x = np.array([3, 1, 2])
print(np.argsort(x))              # 返回排序后元素的原下标
x[np.argsort(x)]                    # 返回排序后的数组

[1 2 0]


array([1, 2, 3])

In [25]:
x.argmax(), x.argmin()      # 最大值和最小值的下标

(0, 1)

In [26]:
print(np.where(x>1))        # 返回满足条件的元素下标

(array([0, 2], dtype=int64),)


In [27]:
x.sort()                    # 原地排序
print(x)

[1 2 3]


#### np.asarray(a, dtype=None, order=None): 
将结构数据转化为ndarray
* a：可以是列表、列表的元组、元组、元组的元组、元组的列表或多维数组
* dtype：数据类型，默认的是自己从输入的数据自动获得
    * 'f'：float类型
    * 'i'：int类型
* order：有"C"和"F"两个选项,分别代表，行优先和列优先，在计算机内存中的存储元素的顺序

In [4]:
a= [1,2]
np.asarray(a,'f')

array([1., 2.], dtype=float32)

In [5]:
a = [[1,2],[1,0]]
a = np.asarray(a)#必须先转换为array，否则出现array(1.0, dtype=float32)
np.asarray(a>0,'i')#'i'表示为dtype类型为int

array([[1, 1],
       [1, 0]], dtype=int32)

In [6]:
np.asarray(a>0,'f')

array([[1., 1.],
       [1., 0.]], dtype=float32)